"""doppy-di: minimal dependency injection container."""

from .auto_wiring import (
    MissingAnnotationError,
    UnresolvableDependencyError,
    injectable,
    is_injectable,
)
from .configuration import AsyncConfiguration, Configuration, ConfigurationError
from .container import (
    AsyncDependencyInSyncContextError,
    AsyncScope,
    CompilePolicy,
    CompositeRuleSet,
    Container,
    ContainerBuilder,
    ContainerConfig,
    CycleError,
    CyclicDependencyError,
    DependencyCycleError,
    DiffReport,
    DuplicateKeyError,
    DuplicateKeyPolicy,
    DuplicateRegistrationError,
    Factory,
    FactoryExecutionError,
    InvalidFactoryError,
    InvalidLifetimeError,
    Key,
    KeyProtocol,
    Lifetime,
    LifetimePolicy,
    MissingDependencyError,
    OverrideContext,
    Provider,
    Qualifier,
    RegistrationSource,
    ResolutionCancelledError,
    ResolveContext,
    ResourceFinalizationError,
    Rule,
    RuleSet,
    Scope,
    ScopePolicy,
    ScopeViolationError,
    ServiceNotFoundError,
    SyncFactoryReturningAwaitableError,
    TracerFn,
    UnregisteredDependencyError,
    UnregisteredTypeError,
    ValidationError,
    YieldNotCalledError,
)
from .devkit import (
    ChildrenFirstPolicy,
    LoggingContainer,
    NestedPolicy,
    NestedRules,
    OrderPolicy,
    ParentFirstPolicy,
    SameObjectPolicy,
    SameValuePolicy,
    UnorderedPolicy,
    ValidatingContainer,
    ValidationRule,
    ValidationRunner,
)
from .graph import DependencyGraph
from .inject import Depends, inject
from .plan import ExecutionPlan
from .resolution import (
    ChildrenFirstPolicy as ResolutionChildrenFirstPolicy,
)
from .resolution import (
    DefaultResolutionPolicy,
    EagerPolicy,
    LazyPolicy,
    ParallelPolicy,
    ResolutionPolicy,
)
from .resolution import (
    ParentFirstPolicy as ResolutionParentFirstPolicy,
)

__all__ = [
    "AsyncConfiguration",
    "AsyncDependencyInSyncContextError",
    "AsyncScope",
    "ChildrenFirstPolicy",
    "CompilePolicy",
    "CompositeRuleSet",
    "Configuration",
    "ConfigurationError",
    "Container",
    "ContainerBuilder",
    "ContainerConfig",
    "CycleError",
    "CyclicDependencyError",
    "DefaultResolutionPolicy",
    "DependencyCycleError",
    "DependencyGraph",
    "Depends",
    "DiffReport",
    "DuplicateKeyError",
    "DuplicateKeyPolicy",
    "DuplicateRegistrationError",
    "EagerPolicy",
    "ExecutionPlan",
    "Factory",
    "FactoryExecutionError",
    "InvalidFactoryError",
    "InvalidLifetimeError",
    "Key",
    "KeyProtocol",
    "LazyPolicy",
    "Lifetime",
    "LifetimePolicy",
    "LoggingContainer",
    "MissingAnnotationError",
    "MissingDependencyError",
    "NestedPolicy",
    "NestedRules",
    "OrderPolicy",
    "OverrideContext",
    "ParallelPolicy",
    "ParentFirstPolicy",
    "Provider",
    "Qualifier",
    "RegistrationSource",
    "ResolutionCancelledError",
    "ResolutionChildrenFirstPolicy",
    "ResolutionParentFirstPolicy",
    "ResolutionPolicy",
    "ResolveContext",
    "ResourceFinalizationError",
    "Rule",
    "RuleSet",
    "SameObjectPolicy",
    "SameValuePolicy",
    "Scope",
    "ScopePolicy",
    "ScopeViolationError",
    "ServiceNotFoundError",
    "SyncFactoryReturningAwaitableError",
    "TracerFn",
    "UnorderedPolicy",
    "UnregisteredDependencyError",
    "UnregisteredTypeError",
    "UnresolvableDependencyError",
    "ValidatingContainer",
    "ValidationError",
    "ValidationRule",
    "ValidationRunner",
    "YieldNotCalledError",
    "inject",
    "injectable",
    "is_injectable",
]
