"""doppy-di: minimal dependency injection container."""

from .auto_wiring import (
    MissingAnnotationError,
    UnresolvableDependencyError,
    injectable,
)
from .container import (
    Container,
    ContainerBuilder,
    ContainerConfig,
    CycleError,
    DuplicateKeyError,
    DuplicateKeyPolicy,
    Key,
    KeyProtocol,
    Lifetime,
    LifetimePolicy,
    OverrideContext,
    ResolveContext,
    Rule,
    RuleSet,
    Scope,
    ScopePolicy,
    ServiceNotFoundError,
)
from .devkit import (
    ChildrenFirstPolicy,
    LoggingContainer,
    NestedPolicy,
    NestedRules,
    OrderPolicy,
    ParentFirstPolicy,
    SameObjectPolicy,
    SameValuePolicy,
    UnorderedPolicy,
    ValidatingContainer,
    ValidationRule,
    ValidationRunner,
)

__all__ = [
    "ChildrenFirstPolicy",
    "Container",
    "ContainerBuilder",
    "ContainerConfig",
    "CycleError",
    "DuplicateKeyError",
    "DuplicateKeyPolicy",
    "Key",
    "KeyProtocol",
    "Lifetime",
    "LifetimePolicy",
    "LoggingContainer",
    "MissingAnnotationError",
    "NestedPolicy",
    "NestedRules",
    "OrderPolicy",
    "OverrideContext",
    "ParentFirstPolicy",
    "ResolveContext",
    "Rule",
    "RuleSet",
    "SameObjectPolicy",
    "SameValuePolicy",
    "Scope",
    "ScopePolicy",
    "ServiceNotFoundError",
    "UnorderedPolicy",
    "UnresolvableDependencyError",
    "ValidatingContainer",
    "ValidationRule",
    "ValidationRunner",
    "injectable",
]
